// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOE0f5p_qcNweUizXEqdwiPa55mM698lQ',
    appId: '1:648547727696:web:496de0fbe19adbb95cd455',
    messagingSenderId: '648547727696',
    projectId: 'loyalty-card-wallet-6a27e',
    authDomain: 'loyalty-card-wallet-6a27e.firebaseapp.com',
    storageBucket: 'loyalty-card-wallet-6a27e.firebasestorage.app',
    measurementId: 'G-6Z5ZHHDQ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVztep6msThSfYkCov2vLtNhqKNckdBEM',
    appId: '1:648547727696:android:10a2286695578ec15cd455',
    messagingSenderId: '648547727696',
    projectId: 'loyalty-card-wallet-6a27e',
    storageBucket: 'loyalty-card-wallet-6a27e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZ0MiamlY4xJVBxfbZ7MqirtjTgRre4o',
    appId: '1:648547727696:ios:a38ddda3acf3ecf95cd455',
    messagingSenderId: '648547727696',
    projectId: 'loyalty-card-wallet-6a27e',
    storageBucket: 'loyalty-card-wallet-6a27e.firebasestorage.app',
    iosBundleId: 'com.example.externalMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZ0MiamlY4xJVBxfbZ7MqirtjTgRre4o',
    appId: '1:648547727696:ios:a38ddda3acf3ecf95cd455',
    messagingSenderId: '648547727696',
    projectId: 'loyalty-card-wallet-6a27e',
    storageBucket: 'loyalty-card-wallet-6a27e.firebasestorage.app',
    iosBundleId: 'com.example.externalMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOE0f5p_qcNweUizXEqdwiPa55mM698lQ',
    appId: '1:648547727696:web:32a8b06bb4d85ec15cd455',
    messagingSenderId: '648547727696',
    projectId: 'loyalty-card-wallet-6a27e',
    authDomain: 'loyalty-card-wallet-6a27e.firebaseapp.com',
    storageBucket: 'loyalty-card-wallet-6a27e.firebasestorage.app',
    measurementId: 'G-70FEM5GHVQ',
  );
}
